### ISSUE TITLE
This store is closed [1.4.200/4]

### ISSUE THREAD

**Issue by Sanantita** [nitrite/nitrite-java#315] opened 2020-09-14 21:17 UTC
Hi there...

I'm running a service in production with a **nitritedb** database for temporary storage. In random times my service throws the following error:

**Caused by: java.lang.IllegalStateException: This store is closed [1.4.200/4]**
java.lang.IllegalStateException: This store is closed [1.4.200/4]
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.IllegalStateException: This store is closed [                                                                                             1.4.200/4]]

I've tried to store db in memory and file with same results. Also tried to remove the save buffer. What is the exact cause for this error? I cannot get the exact moment when it occurs.

Thanks in advance!

**Comment by anidotnet** [comment] 2020-09-15 05:35
It can happen, when you are running db operation on a thread and some unhandled error occurred which is closing the store, or you are closing the store prematurely in your code.

If you still cannot pinpoint the issue, try to provide some reproducible code here.

**Comment by as250648** [comment] 2020-09-15 11:37
Thanks @anidotnet. 

I can't reproduce in my environment, it only happens randomly in production. I have two questions based in your answer:

1.- So, it happens when an unhandled error occurs in a thread. Does that refer to any kind of error or one from nitritedb exclusively?

2.- There is any way to recover from this error? I tried to detect when the Repository is closed, close and open the db, but doesn't work.

Thank you!

**Comment by Sanantita** [comment] 2020-09-15 11:44
Thanks @anidotnet 

I can't reproduce in my environment, it only happens randomly in production. I have two questions based in your answer:

1.- So, it happens when an unhandled error occurs in a thread. Does that refer to any kind of error or one from nitritedb exclusively?

2.- There is any way to recover from this error? I tried to detect when the Repository is closed, close and open the db, but doesn't work.

Thank you!

**Comment by anidotnet** [comment] 2020-09-15 11:59
An error can occurs from any part of your code, it can be any nitrite specific exception or any other exception from your code. I can't say anything specific, unless I see the actual code.

What you can do is, wrap your runnable code in a try catch block and gracefully handle the exception. Also try to collect more details from your application when the error occurs like full stacktraces etc.

**Comment by anidotnet** [comment] 2020-09-24 13:02
Closing the issue due to inactivity. If you find anymore details, please feel free to re-open this issue.

**Closed by anidotnet** 2020-09-24 13:02 UTC
