### ISSUE TITLE
Crash due to ClosedChannelException

### ISSUE THREAD

**Issue by amircoder** [nitrite/nitrite-java#505] opened 2021-04-05 14:01 UTC
I got crash due to the ClosedChannelException, I think the reason is that two threads are accessing an open collection.
The crash place is :
org.h2.store.fs.FileNio.read (FileNio.java:74)
Please look at the stack trace:

```
sun.nio.ch.FileChannelImpl.ensureOpen (FileChannelImpl.java:133)
sun.nio.ch.FileChannelImpl.read (FileChannelImpl.java:772)
org.h2.store.fs.FileNio.read (FileNio.java:74)
org.h2.mvstore.DataUtils.readFully (DataUtils.java:442)
org.h2.mvstore.FileStore.readFully (FileStore.java:98)
org.h2.mvstore.Chunk.readBufferForPage (Chunk.java:361)
org.h2.mvstore.MVStore.readBufferForPage (MVStore.java:1214)
org.h2.mvstore.MVStore.readPage (MVStore.java:2209)
org.h2.mvstore.MVMap.readPage (MVMap.java:672)
org.h2.mvstore.MVMap.readOrCreateRootPage (MVMap.java:688)
org.h2.mvstore.MVMap.setRootPos (MVMap.java:682)
org.h2.mvstore.MVStore.openMap (MVStore.java:576)
org.h2.mvstore.MVStore.openMap (MVStore.java:535)
org.h2.mvstore.MVStore.openMap (MVStore.java:516)
org.dizitart.no2.store.NitriteMVStore.openMap (NitriteMVStore.java:89)
org.dizitart.no2.internals.IndexMetaService.getIndexMetadata (IndexMetaService.java:152)
org.dizitart.no2.internals.IndexMetaService.hasIndex (IndexMetaService.java:60)
org.dizitart.no2.internals.NitriteService.hasIndex (NitriteService.java:93)
org.dizitart.no2.internals.DefaultNitriteCollection.hasIndex (DefaultNitriteCollection.java:114)

com.myapp.app.AppConfigNamespace.<init> (AppConfigNamespace.java:19)
com.myapp.app.AppConfig.getNamespace (AppConfig.java:70)
com.myapp.core.WalletConfig.<init> (WalletConfig.java:59)
com.myapp.core.WalletConfig.getInstance (WalletConfig.java:45)
com.myapp.wallet.models.AccountModel.<init> (AccountModel.java:37)
```

[There is another similar issue but no answer is provided.](https://github.com/nitrite/nitrite-java/issues/80)

I can't reproduce this crash, but what I guess is that the crash happens when two threads one the main and another an android service are trying to access the nitrite collection.
Can you suggest a generic way to handle this crash?
Also there are some discussion about H2 database and the problem with NIO and interrupted thread, I think that's a related topic as well.

**Comment by anidotnet** [comment] 2021-04-05 14:37
Nothing can be done from Nitrite's end for this. The issue is happening because db file is closed in one thread and other thread is trying to access it. Though there is a check to see if the db file is opened in every collection api, but it will not be helpful in these case as multiple threads are trying to access the collection simultaneously.

One thing you can do as I have suggested in the other issue - disable the shut down hook. In that case when you close an activity, it will not close the db. But you need to manually close the db at a proper time in your app's life-cycle. And try to synchronize the db calls as much as possible so that multiple threads are not calling collection apis unless it is absolutely necessary.

**Comment by amircoder** [comment] 2021-04-05 14:47
Ok, thank you for the response.

**Closed** 2021-06-06 16:34 UTC
